import { reactive } from "vue";

export const fontLoadTimeout = 500;
export const fontNames = [
  "Aldrich",
  "Alfa Slab One",
  "Azeret Mono",
  "Bevan",
  "Black Ops One",
  "Bungee",
  "Caesar Dressing",
  "Cinzel Decorative",
  "Fredericka the Great",
  "Geostar Fill",
  "Keania One",
  "Londrina Shadow",
  "Luckiest Guy",
  "Metal Mania",
  "Passion One",
  "Righteous",
  "Rubik Wet Paint",
  "Spicy Rice",
  "Stalinist One",
  "Stardos Stencil",
  "Ultra",
  "Vast Shadow",
  "Wallpoet",
  "Zen Dots",
];

export const store = reactive({
  fontNames,
  fontsLoaded: false,
  drawCrosshair: false,
  glyphs: {
    fontFamily: fontNames[0],
    fontSize: "120",
    shadowSize: 4,
    shadowColor: "#000000",
    size: 128,
    offsetX: 0,
    offsetY: 0,
  },
  centerHelperColor: "#00ff00",
  previewBgColor: "#777777",
  numColorTop: "#ffffff",
  numColorBottom: "#aaaaaa",
  anumColorTop: "#ff0000",
  anumColorBottom: "#aa0000",
});
